### PR TITLE
Adds basic auth

### PR DESCRIPTION
**Pull request by gkanwar**
Addressing issue #56 

This sets up basic 401 auth to access the Omniboard views. User/pass/secret are specified via a command-line option.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@gkanwar Thanks for the PR! Can you also update the documentation with an example on how to setup basic auth? You can find relevant doc here - https://github.com/vivekratnavel/omniboard/blob/master/docs/quick-start.md

Also, I believe we need changes to `web` as well to handle the 401 error and to have the correct auth headers while sending queries to the server. Is that correct?

**Comment by gkanwar** [comment]
Docs updated!

No changes to web required I believe. This just uses the browser built-in handling for basic auth, and express-session to maintain authentication across a session.

**Comment by vivekratnavel** [comment]
@gkanwar I tested the changes locally and the changes look good to me except a minor thing. I don't see yarn.lock file updated in your commits. Can you run "yarn install" from omniboard root and check in the updated yarn.lock file? Thanks!

**Comment by gkanwar** [comment]
Done!

**Pull request merged**
