### PR TITLE
live_reload #57 WIP

### PR DESCRIPTION
**Pull request by kilsenp**
This is to keep track of implementing a live reload. A am not sure if this current work in progress is any good.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
Hi @kilsenp,

Thank you for this initiative! I have merged this feature via #91 

Omniboard can now fetch incremental updates and you can configure the auto refresh interval in settings. Please give it a try and let me know your feedback.

**Comment by kilsenp** [comment]
Awesome! Looks great! Thanks a lot!
I noticed one minor bug, if you update the settings for the auto reload interval it should also call _startPolling method.
I had set it to 9999 to effectively turn it off, and now for a long time does not set this new timeout.

**Comment by vivekratnavel** [comment]
Sure! Will fix it tonight

**Comment by vivekratnavel** [comment]
@kilsenp Thanks for trying out and reporting the bug! It is now fixed via #92

**Pull request closed without merging**
