### PR TITLE
WIP: Improve metrics plot

### LINKED ISSUE #266: Improving metrics plot
# Description
I have been using Omniboard for a while now and find it very useful. However, one thing that has been bothering me are some details related to the metrics plot. They become especially visible when comparing multiple runs:

  - The plot color cycle seems weird as it repeats green very early on or the two different greens are extremely close (for both single metrics plot and compare metrics plot)
  - Metrics from the same experiment are differently colored
  - Plots are incorrectly joined when not explicitly sorting by id, see #218 
 
To illustrate the first two points, see this example:
metrics_plot

# Possible solution
  - Alter the color cycle such that there is more contrast in the first colors, or is this a request better put with plotly?
  - Use the same color for different runs in the compare metrics view but different markers or linestyles (e.g. circles, diamonds, etc .or dashed and dotted lines).
  - Possibly group the legend by run id

### PR DESCRIPTION
**Pull request by MaxSchambach**
# Description
Improving the metrics plot. 
Closes #266 

## Update color palette
The color palette is updated to the `colorblind` palette of [Seaborn](https://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes).
It offers a much better contrast.

## Group metrics from the same experiment
In the `Compare metrics` view, plot the metrics from the same experiment using the same color but different line styles for the different metrics. This way, comparison of multiple metrics across multiple experiments is improved significantly.
Available line styles in plotly, according to the [documentation](https://plotly.com/javascript/line-charts/):

  - `solid`
  - `dash`
  - `dashdot`

Maybe there are more?

# Todo
- [x]  Update color palette
- [x] Group metrics from the same experiment

### CODE REVIEW

**Comment by MaxSchambach** [comment]
Unfortunately, I am not able to build the development server iwth the current release to work on the grouping of experiments in the `compare metrics` window. Also, I'm not proficient in JS, so maybe you have a quicker solution @vivekratnavel ?
Otherwise, I would need some time to work on this and to get the development server running.

**Comment by vivekratnavel** [comment]
Hi @MaxSchambach, thank you for initiating this PR. I will try to help you out to complete this PR.

**Comment by vivekratnavel** [comment]
@MaxSchambach It will be great if you can give me permissions to push commits to this PR branch - https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by MaxSchambach** [comment]
@vivekratnavel great, thanks!
You should already have permission to push to this branch.

**Comment by vivekratnavel** [comment]
@MaxSchambach Metrics from the same Run ID can now be assigned a different plot mode. Check it out and let me know how you like it.
Screen Shot 2021-07-30 at 1 11 08 AM

**Comment by MaxSchambach** [comment]
@vivekratnavel thanks for the work! However, it's not quite what I had in mind, as it does not quite help when comparing multiple runs and metrics. To show, what I thought of, maybe the attached mockup helps.

Here, all plots from the same experiment use the same color so that they can easily be attributed to a single experiment.
And all metrics, across different experiments, use the same linestyle (for which plotly provides `solid`, `dash` and `dashdot` as far as I can tell). This way, identical metrics can easily be identified and compared across the different experiments.
This would be pretty great, as I often find myself comparing multiple runs over multiple metrics. Since I think comparing more than three metrics would clutter everything, the three provided linestyles should suffice.

Do you think this is implementable without too much hassle?

testfig

**Comment by vivekratnavel** [comment]
Done. You can now use dash or dot.
 
Screen Shot 2021-07-30 at 10 06 12 AM

**Comment by MaxSchambach** [comment]
Thanks! It's not fully what I was thinking of, but it does improve things.

**Pull request merged**
